services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,lambda,apigateway,cloudformation,sts,iam,cloudfront,cognito-idp,rds,secretsmanager,ssm,events,appsync,ec2,logs
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=false
      - PERSISTENCE=1
      - AWS_DEFAULT_REGION=us-west-2
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network

  postgres:
    image: "public.ecr.aws/docker/library/postgres:16"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge

volumes:
  mysql_data:
  postgres_data:
